### ISSUE TITLE
agg combined with django-filters

### ISSUE THREAD

**Issue by Eloi-Marin** [ABASystems/django-rest-framework-aggregates#3]
Great library!

I am trying to apply a group_by and aggregation while filtering data. How should I do that? My intuition goes for something like:

endpoint.agg/?order_date_0=2018-01-01&order_date_1=2018-03-30&group_by[country]&group_by[province]&aggregate[sum]=gdp

but it's not working. Is there a way to make your library compatible with django-filters?

**Comment by tabby-or-not** [comment]
The only problem I can see with your query is that sum should be capitalised (to match the `django.db.models.aggregates` functions).

What sort of output are you getting? Django filters should be working already as per your existing api setup.

**Comment by Eloi-Marin** [comment]
Hi !! Thanks for your answer !


Yeah, I changed the capitalization on purpose, just to avoid capitals in the url. Nothing relevant, I set it back to the original setting now.


So this is my view:


class OrdersViewSet(viewsets.ModelViewSet):
    queryset = Orders.objects.all()
    serializer_class = OrdersSerializer
    filter_fields = (
        'order_date',
       )

    def list(self, request, *args, **kwargs):
        renderer = request.accepted_renderer
        if isinstance(renderer, AggregateRenderer):
            queryset = self.filter_queryset(self.get_queryset())
            try:
                data = request.accepted_renderer.render({
                    'queryset': queryset, 'request': request
                })
            except AggregateException as e:
                # Raise other types of aggregate errors
                return Response(str(e), status=400)
            return Response(data, content_type=f'application/json')
        return super().list(request, *args, **kwargs)

The URL, now without group by's:

orders.agg/?order_date_0=2018-01-01&order_date_1=2018-03-30&aggregate[Sum]=gross_sales

And the response is:

{"data": {"sum_gross_sales": 1451849.96000003}}

exactly the same as in the case without filtering the dates:

orders.agg/?aggregate[Sum]=gross_sales

response:


{"data": {"sum_gross_sales": 1451849.96000003}}

However the original endpoint:

orders/?order_date_0=2018-01-01&order_date_1=2018-03-30

returns 9840 items in the browsable API, while there are 40084 items without filtering the date interval, therefore the aggregate[Sum] should definitely give a different result.

Is there any other information I could provide you so you can help me track the bug? I am not getting any error anywhere, only the view is ignoring the filter somehow...

Thaank you so much again!

**Comment by Eloi-Marin** [comment]
Hi again,


Sorry, I was just testing other cases:


?shift=dinner&aggregate[Sum]=gross_sales


this other filter DOES work, so that's awesome :D It seems the only problem is with interval filtering, which is a non basic case of django-filters...






________________________________

**Comment by Eloi-Marin** [comment]
Ok, issue is over, my apologies, all my fault..
I wasn't declaring filters.DateFromToRangeFilter() correctly, shame on me.

Everything works wonderfully :)

**Comment by tabby-or-not** [comment]
Great to hear :) Do let us know if you run into any issues or come up with any improvements that could be made :)
